apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pluscode-autoscaler
spec:
  minReplicas: 2
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: robohash
  targetCPUUtilizationPercentage: 40
