apiVersion: apps/v1
kind: Deployment
metadata:
  name: pluscode-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pluscode
  template:
    metadata:
      labels:
        app: pluscode
    spec:
      containers:
      - name: pluscode-container
        image: server_app:latest
        imagePullPolicy: Never