apiVersion: apps/vi
kind: Deployment
metadata:
  name: pluscode
spec:
  replicas: 3
  selector:
    matchLabels:
      name: pluscode
  template:
    metadata:
      labels:
        labels:
          name: pluscode
    spec:
      containers:
      - name: pluscode-container
        image: wdenniss/pluscode-demo:latest
        resources:
          cpu: 200m
          memory: 250Mi

